name: packer

on:
  push:

env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Ocean Packer
    env:
      aws-access-key-id: AKIA6L5PPUMFDXJUOMX5
      aws-secret-access-key: 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
      aws-region: ap-south-1  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: packer init .
        working-directory: ./packer/

      - name: Run `packer validate`
        id: validate
        run: packer validate .
        working-directory: ./packer/

      - name: Run `packer build image`
        id: build
        run: packer build .
        working-directory: ./packer/
  
